package com.sakena.support.domain.model

import com.sakena.shared.domain.DomainValidationException
import com.sakena.user.domain.UserId
import java.time.Instant
import java.util.UUID

@JvmInline
value class TicketMessageId(val value: UUID) {
    override fun toString(): String = value.toString()

    companion object {
        fun new() = TicketMessageId(UUID.randomUUID())
    }
}

/** What a message carries — plain text or an object-storage attachment. */
enum class TicketMessageKind {
    TEXT,
    IMAGE,
    VOICE,
}

/**
 * An attachment stored in object storage. The aggregate keeps only the storage
 * key and metadata; the bytes live in MinIO and are served through short-lived
 * presigned URLs generated by the infrastructure layer.
 */
data class TicketAttachment(
    val storageKey: String,
    val contentType: String,
    val sizeBytes: Long,
    /** Voice-note length in seconds; null for images. */
    val durationSeconds: Int?,
) {
    init {
        if (storageKey.isBlank()) throw DomainValidationException("Attachment storage key must not be blank")
        if (contentType.isBlank()) throw DomainValidationException("Attachment content type must not be blank")
        if (sizeBytes <= 0) throw DomainValidationException("Attachment must not be empty")
    }
}

/**
 * One turn in a support ticket's thread. Messages are immutable: a support
 * conversation is a record of what was actually said, so nothing here can be
 * edited or deleted after the fact.
 */
class TicketMessage private constructor(
    val id: TicketMessageId,
    val ticketId: TicketId,
    val authorId: UserId,
    val kind: TicketMessageKind,
    val body: String?,
    val attachment: TicketAttachment?,
    val sentAt: Instant,
) {
    companion object {
        const val MAX_BODY_LENGTH = 2000

        fun text(
            ticketId: TicketId,
            authorId: UserId,
            body: String,
            now: Instant = Instant.now(),
        ): TicketMessage = TicketMessage(
            id = TicketMessageId.new(),
            ticketId = ticketId,
            authorId = authorId,
            kind = TicketMessageKind.TEXT,
            body = validateBody(body),
            attachment = null,
            sentAt = now,
        )

        fun withAttachment(
            ticketId: TicketId,
            authorId: UserId,
            kind: TicketMessageKind,
            attachment: TicketAttachment,
            now: Instant = Instant.now(),
        ): TicketMessage {
            if (kind == TicketMessageKind.TEXT) {
                throw DomainValidationException("An attachment message must be an image or a voice note")
            }
            return TicketMessage(
                id = TicketMessageId.new(),
                ticketId = ticketId,
                authorId = authorId,
                kind = kind,
                body = null,
                attachment = attachment,
                sentAt = now,
            )
        }

        /** Rebuilds an aggregate from already-persisted state. No invariants are re-checked. */
        fun reconstitute(
            id: TicketMessageId,
            ticketId: TicketId,
            authorId: UserId,
            kind: TicketMessageKind,
            body: String?,
            attachment: TicketAttachment?,
            sentAt: Instant,
        ) = TicketMessage(id, ticketId, authorId, kind, body, attachment, sentAt)

        private fun validateBody(body: String): String {
            val trimmed = body.trim()
            if (trimmed.isEmpty()) throw DomainValidationException("Message body must not be blank")
            if (trimmed.length > MAX_BODY_LENGTH) {
                throw DomainValidationException("Message body must be at most $MAX_BODY_LENGTH characters")
            }
            return trimmed
        }
    }
}
