package com.sakena.announcement.infrastructure.persistence

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.Instant
import java.util.UUID

/**
 * JPA persistence model. Deliberately separate from the domain
 * [com.sakena.announcement.domain.model.Announcement] so that database/ORM
 * concerns never leak into the domain. The no-arg constructor and `open`
 * modifiers are generated by the kotlin-jpa / all-open plugins.
 */
@Entity
@Table(name = "announcements")
class AnnouncementEntity(
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    var id: UUID,

    @Column(name = "title", nullable = false, length = 200)
    var title: String,

    @Column(name = "body", nullable = false, length = 4_000)
    var body: String,

    @Column(name = "created_by", nullable = false)
    var createdBy: UUID,

    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: Instant,
)
