package com.sakena.chat.domain.model

import com.sakena.property.domain.model.BuildingId
import com.sakena.shared.domain.DomainConflictException
import com.sakena.shared.domain.DomainValidationException
import com.sakena.user.domain.UserId
import java.time.Instant
import java.util.UUID

/** Value object identifying a [ChatMessage] aggregate. */
@JvmInline
value class ChatMessageId(val value: UUID) {

    override fun toString(): String = value.toString()

    companion object {
        fun new(): ChatMessageId = ChatMessageId(UUID.randomUUID())

        fun from(raw: String): ChatMessageId =
            try {
                ChatMessageId(UUID.fromString(raw))
            } catch (e: IllegalArgumentException) {
                throw DomainValidationException("'$raw' is not a valid message id")
            }
    }
}

/** What a message carries — plain text or an object-storage attachment. */
enum class ChatMessageKind {
    TEXT,
    IMAGE,
    VOICE,
}

/**
 * An attachment stored in object storage. The aggregate keeps only the storage
 * key and metadata; the bytes live in MinIO and are served through short-lived
 * presigned URLs generated by the infrastructure layer.
 */
data class ChatAttachment(
    val storageKey: String,
    val contentType: String,
    val sizeBytes: Long,
    /** Voice-note length in seconds; null for images. */
    val durationSeconds: Int?,
) {
    init {
        if (storageKey.isBlank()) throw DomainValidationException("Attachment storage key must not be blank")
        if (contentType.isBlank()) throw DomainValidationException("Attachment content type must not be blank")
        if (sizeBytes <= 0) throw DomainValidationException("Attachment must not be empty")
    }
}

/**
 * ChatMessage aggregate root — one message in a building's group chat.
 *
 * Authors may edit and delete their own messages; the building manager may
 * delete anyone's. Deletion is soft (tombstone) so the conversation keeps its
 * shape and an edited message always shows when it was last changed.
 */
class ChatMessage private constructor(
    val id: ChatMessageId,
    val buildingId: BuildingId,
    val senderId: UserId,
    val kind: ChatMessageKind,
    body: String?,
    val attachment: ChatAttachment?,
    val sentAt: Instant,
    editedAt: Instant?,
    deletedAt: Instant?,
    deletedBy: UserId?,
) {
    var body: String? = body
        private set

    var editedAt: Instant? = editedAt
        private set

    var deletedAt: Instant? = deletedAt
        private set

    var deletedBy: UserId? = deletedBy
        private set

    val deleted: Boolean get() = deletedAt != null

    val edited: Boolean get() = editedAt != null

    /** Only the author may rewrite a message, and only text messages carry a body. */
    fun editBody(newBody: String, editorId: UserId) {
        requireNotDeleted()
        if (senderId != editorId) {
            throw DomainConflictException("Only the author can edit this message")
        }
        if (kind != ChatMessageKind.TEXT) {
            throw DomainConflictException("Only text messages can be edited")
        }
        body = validateBody(newBody)
        editedAt = Instant.now()
    }

    /** Deletes a message at its author's request. */
    fun deleteByAuthor(authorId: UserId) {
        requireNotDeleted()
        if (senderId != authorId) {
            throw DomainConflictException("Only the author or the building manager can delete this message")
        }
        markDeletedBy(authorId)
    }

    /** Deletes a message as a building-manager moderation action. */
    fun deleteByManager(managerId: UserId) {
        requireNotDeleted()
        markDeletedBy(managerId)
    }

    /**
     * Compatibility entry point while callers migrate to the intention-revealing
     * author and manager operations.
     */
    fun delete(requesterId: UserId, requesterIsManager: Boolean) {
        if (requesterIsManager) {
            deleteByManager(requesterId)
        } else {
            deleteByAuthor(requesterId)
        }
    }

    private fun markDeletedBy(requesterId: UserId) {
        deletedAt = Instant.now()
        deletedBy = requesterId
    }

    private fun requireNotDeleted() {
        if (deleted) throw DomainConflictException("This message has already been deleted")
    }

    companion object {
        const val MAX_BODY_LENGTH = 4_000

        fun text(buildingId: BuildingId, senderId: UserId, body: String): ChatMessage =
            ChatMessage(
                id = ChatMessageId.new(),
                buildingId = buildingId,
                senderId = senderId,
                kind = ChatMessageKind.TEXT,
                body = validateBody(body),
                attachment = null,
                sentAt = Instant.now(),
                editedAt = null,
                deletedAt = null,
                deletedBy = null,
            )

        fun withAttachment(
            buildingId: BuildingId,
            senderId: UserId,
            kind: ChatMessageKind,
            attachment: ChatAttachment,
            caption: String?,
        ): ChatMessage {
            if (kind == ChatMessageKind.TEXT) {
                throw DomainValidationException("An attachment message must be an image or a voice note")
            }
            return ChatMessage(
                id = ChatMessageId.new(),
                buildingId = buildingId,
                senderId = senderId,
                kind = kind,
                body = caption?.trim()?.ifEmpty { null }?.also { validateBody(it) },
                attachment = attachment,
                sentAt = Instant.now(),
                editedAt = null,
                deletedAt = null,
                deletedBy = null,
            )
        }

        /** Rebuilds an aggregate from already-persisted state. No invariants are re-checked. */
        fun reconstitute(
            id: ChatMessageId,
            buildingId: BuildingId,
            senderId: UserId,
            kind: ChatMessageKind,
            body: String?,
            attachment: ChatAttachment?,
            sentAt: Instant,
            editedAt: Instant?,
            deletedAt: Instant?,
            deletedBy: UserId?,
        ): ChatMessage = ChatMessage(
            id, buildingId, senderId, kind, body, attachment, sentAt, editedAt, deletedAt, deletedBy,
        )

        private fun validateBody(body: String): String {
            val trimmed = body.trim()
            if (trimmed.isEmpty()) throw DomainValidationException("Message text must not be blank")
            if (trimmed.length > MAX_BODY_LENGTH) {
                throw DomainValidationException("Message text must be at most $MAX_BODY_LENGTH characters")
            }
            return trimmed
        }
    }
}
