package com.sakena.billing.domain.model

import com.sakena.property.domain.model.BuildingId
import com.sakena.shared.domain.DomainConflictException
import com.sakena.shared.domain.DomainValidationException
import java.time.Instant
import java.time.LocalDate

/** How often a period recurs — drives the manager's default date range only. */
enum class ChargePeriodType {
    MONTHLY,
    QUARTERLY,
    CUSTOM,
}

/**
 * Lifecycle of a [ChargePeriod]. Cost lines may only be edited while the
 * period is still DRAFT; issuing freezes them into per-unit invoices.
 */
enum class ChargePeriodStatus {
    DRAFT,
    ISSUED,
    CLOSED,
    ;

    fun canTransitionTo(target: ChargePeriodStatus): Boolean =
        when (this) {
            DRAFT -> target == ISSUED
            ISSUED -> target == CLOSED
            CLOSED -> false
        }
}

/**
 * ChargePeriod aggregate root — a billing window (monthly, quarterly or
 * custom) the manager collects charges for. Cost lines are attached while it
 * is DRAFT; issuing allocates them across units and closes editing.
 */
class ChargePeriod private constructor(
    val id: ChargePeriodId,
    val buildingId: BuildingId,
    title: String,
    val type: ChargePeriodType,
    startsOn: LocalDate,
    endsOn: LocalDate,
    status: ChargePeriodStatus,
    val createdAt: Instant,
    updatedAt: Instant,
) {
    var title: String = title
        private set

    var startsOn: LocalDate = startsOn
        private set

    var endsOn: LocalDate = endsOn
        private set

    var status: ChargePeriodStatus = status
        private set

    var updatedAt: Instant = updatedAt
        private set

    val editable: Boolean get() = status == ChargePeriodStatus.DRAFT

    fun reschedule(newTitle: String, newStartsOn: LocalDate, newEndsOn: LocalDate) {
        requireEditable("reschedule")
        this.title = validateTitle(newTitle)
        validateRange(newStartsOn, newEndsOn)
        this.startsOn = newStartsOn
        this.endsOn = newEndsOn
        touch()
    }

    /** Freezes the cost lines; invoices are generated by the application service. */
    fun issue() {
        transitionTo(ChargePeriodStatus.ISSUED)
    }

    /** Marks the period as financially settled — no further payments expected. */
    fun close() {
        transitionTo(ChargePeriodStatus.CLOSED)
    }

    private fun transitionTo(target: ChargePeriodStatus) {
        if (!status.canTransitionTo(target)) {
            throw DomainConflictException("Cannot move charge period from $status to $target")
        }
        status = target
        touch()
    }

    private fun requireEditable(action: String) {
        if (!editable) {
            throw DomainConflictException("Cannot $action a charge period that is already $status")
        }
    }

    private fun touch() {
        updatedAt = Instant.now()
    }

    companion object {
        const val MAX_TITLE_LENGTH = 150

        fun create(
            buildingId: BuildingId,
            title: String,
            type: ChargePeriodType,
            startsOn: LocalDate,
            endsOn: LocalDate,
        ): ChargePeriod {
            validateRange(startsOn, endsOn)
            val now = Instant.now()
            return ChargePeriod(
                id = ChargePeriodId.new(),
                buildingId = buildingId,
                title = validateTitle(title),
                type = type,
                startsOn = startsOn,
                endsOn = endsOn,
                status = ChargePeriodStatus.DRAFT,
                createdAt = now,
                updatedAt = now,
            )
        }

        /** Rebuilds an aggregate from already-persisted state. No invariants are re-checked. */
        fun reconstitute(
            id: ChargePeriodId,
            buildingId: BuildingId,
            title: String,
            type: ChargePeriodType,
            startsOn: LocalDate,
            endsOn: LocalDate,
            status: ChargePeriodStatus,
            createdAt: Instant,
            updatedAt: Instant,
        ): ChargePeriod =
            ChargePeriod(id, buildingId, title, type, startsOn, endsOn, status, createdAt, updatedAt)

        private fun validateTitle(title: String): String {
            val trimmed = title.trim()
            if (trimmed.isEmpty()) throw DomainValidationException("Charge period title must not be blank")
            if (trimmed.length > MAX_TITLE_LENGTH) {
                throw DomainValidationException("Charge period title must be at most $MAX_TITLE_LENGTH characters")
            }
            return trimmed
        }

        private fun validateRange(startsOn: LocalDate, endsOn: LocalDate) {
            if (!endsOn.isAfter(startsOn)) {
                throw DomainValidationException("Charge period must end after it starts")
            }
        }
    }
}
