package com.sakena.task.infrastructure.persistence

import com.sakena.task.domain.model.TaskStatus
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.Instant
import java.util.UUID

/**
 * JPA persistence model. Deliberately separate from the domain [com.sakena.task.domain.model.Task]
 * so that database/ORM concerns never leak into the domain. The no-arg constructor
 * and `open` modifiers are generated by the kotlin-jpa / all-open plugins.
 */
@Entity
@Table(name = "tasks")
class TaskEntity(
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    var id: UUID,

    @Column(name = "title", nullable = false, length = 200)
    var title: String,

    @Column(name = "description", length = 2_000)
    var description: String?,

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    var status: TaskStatus,

    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: Instant,

    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant,
)
